apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-demo
  namespace: fleet-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-demo
  template:
    metadata:
      labels:
        app: fleet-demo
    spec:
      containers:
        - name: fleet-demo
          image: mak3r/rancher-demo:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: orange
          readinessProbe:
            httpGet:
              port: web
              path: /
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-demo
  namespace: fleet-demo
spec:
  type: NodePort
  selector:
    app: fleet-demo
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 32001
