apiVersion: v1
kind: Service
metadata:
  name: fleet-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: fleet-demo
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 32001
