apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-demo
  namespace: fleet-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleet-demo
  template:
    metadata:
      labels:
        app: fleet-demo
    spec:
      containers:
        - name: fleet-demo
          image: mak3r/rancher-demo:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: orange
          readinessProbe:
            httpGet:
              port: web
              path: /
---
apiVersion: v1
kind: Service
metadata:
  name: service-fleet-demo
  namespace: fleet-demo
spec:
  type: NodePort
  selector:
    app: fleet-demo
  ports:
  - name: nodeport-fleet-demo
    protocol: TCP
    port: 80 # The port the service exposes internally
    targetPort: 80 # The port the container listens on
    nodePort: 32000 # The port exposed on each Node's IP. Choose a port in the range 30000-32767
